#!/bin/bash
ln -s /proj/genomeanalysis2023/Genome_Analysis/4_Tean_Teh_2017/pacbio_data/SRR6037732_scaffold_06.fq.gz /home/joed4996/Genome_analysis_local_rep/data/raw_external_data/genomic_data/pacbio_data/SRR6037732_scaffold_06.fq.gz
ln -s /proj/genomeanalysis2023/Genome_Analysis/4_Tean_Teh_2017/pacbio_data/SRR6037732_scaffold_10.fq.gz /home/joed4996/Genome_analysis_local_rep/data/raw_external_data/genomic_data/pacbio_data/SRR6037732_scaffold_10.fq.gz
ln -s /proj/genomeanalysis2023/Genome_Analysis/4_Tean_Teh_2017/pacbio_data/SRR6037732_scaffold_11.fq.gz /home/joed4996/Genome_analysis_local_rep/data/raw_external_data/genomic_data/pacbio_data/SRR6037732_scaffold_11.fq.gz

